### ISSUE TITLE
Stores do not update on devtools

### ISSUE THREAD

**Issue by ricdotnet** [iDevelopThings/vue-class-stores#4]
Every time I refresh or navigate somewhere where stores are active they never update. 🤔 
If I run the actions inside, then they update.

---

https://user-images.githubusercontent.com/3798163/196385090-6aa80c2d-ce1f-450c-b970-a20fbd8da747.mov

**Comment by iDevelopThings** [comment]
Should be fixed in https://github.com/iDevelopThings/vue-class-stores/commit/eadceddfef0f3a9f49c9f2df0c23f4ce2c75cda3 re-open if you find any cases where it doesnt ^^
